/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;
import datos.*;
import entidades.Usuario;
import java.sql.*;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showMessageDialog;
import logica.UsuarioBL;
/**
 *
 * @author SERIN
 */
public class Login extends javax.swing.JFrame {
    public static String ID;
    public static String PASSWORD;
    public static String TYPE_USER;
    public static String COD;
    
    private static Connection cn = null;
    private static PreparedStatement ps = null;
    private static Statement st = null;
    private static ResultSet rs = null;
    /**
     * Creates new form Principal
     */
    public Login() {
        initComponents();
        this.setLocationRelativeTo(null);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtID = new javax.swing.JTextField();
        btnIIngresar = new javax.swing.JButton();
        txtPASS = new javax.swing.JPasswordField();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Log in");
        setBackground(java.awt.SystemColor.activeCaption);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setIconImage(new javax.swing.ImageIcon(getClass().getResource("/resources/loginIco.png")).getImage());
        setMinimumSize(new java.awt.Dimension(640, 264));
        setUndecorated(true);
        setResizable(false);
        setType(java.awt.Window.Type.POPUP);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtID.setForeground(new java.awt.Color(255, 255, 255));
        txtID.setToolTipText("USER");
        txtID.setBorder(null);
        txtID.setCaretColor(new java.awt.Color(255, 255, 255));
        txtID.setOpaque(false);
        getContentPane().add(txtID, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 90, 110, 20));

        btnIIngresar.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        btnIIngresar.setForeground(new java.awt.Color(0, 51, 51));
        btnIIngresar.setText("SIGN IN");
        btnIIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIIngresarActionPerformed(evt);
            }
        });
        getContentPane().add(btnIIngresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 180, 150, -1));

        txtPASS.setForeground(new java.awt.Color(255, 255, 255));
        txtPASS.setToolTipText("PASSWORD");
        txtPASS.setBorder(null);
        txtPASS.setCaretColor(new java.awt.Color(255, 255, 255));
        txtPASS.setOpaque(false);
        getContentPane().add(txtPASS, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 110, 20));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/login.jpg"))); // NOI18N
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 260));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIIngresarActionPerformed
        try {
            // TODO add your handling code here:
            ID = txtID.getText();
            PASSWORD = txtPASS.getText();
            
            Usuario usuario = UsuarioBL.iniciarSesion(ID, PASSWORD);
            
            switch (usuario.getUsuaTipo()) {
                case "cliente":
                    FrmCliente frmCliente = new FrmCliente(usuario);
                    frmCliente.setVisible(true);
                    this.dispose();
                    break;
                case "admin":
                    FrmAdministrador frmAdministrador = new FrmAdministrador(usuario);
                    frmAdministrador.setVisible(true);
                    this.dispose();
                    break;
                case "empleado":
                    FrmEmpleado frmEmpleado = new FrmEmpleado(usuario);
                    frmEmpleado.setVisible(true);
                    this.dispose();
                    break;
                default:
                    break;
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, ex.getMessage());
        }
    }//GEN-LAST:event_btnIIngresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //Conexion.Conectar();
                    new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnIIngresar;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JTextField txtID;
    private javax.swing.JPasswordField txtPASS;
    // End of variables declaration//GEN-END:variables
}
