/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.BorderLayout;

/**
 *
 * @author COMPAQ
 */
public class PnlEmp_Control extends javax.swing.JPanel {

    /**
     * Creates new form PnlClie_Control
     */
    public PnlEmp_Control() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrarEmpleado = new javax.swing.JLabel();
        btnModificarEmpleado = new javax.swing.JLabel();
        btnEliminarEmpleado = new javax.swing.JLabel();
        btnCuentasRegistradas = new javax.swing.JLabel();
        btnCuentasRegistradas1 = new javax.swing.JLabel();

        setOpaque(false);

        btnRegistrarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmpleadoRegistrar72.png"))); // NOI18N
        btnRegistrarEmpleado.setToolTipText("REGISTRAR");
        btnRegistrarEmpleado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarEmpleadoMouseClicked(evt);
            }
        });

        btnModificarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmpleadoModificar72.png"))); // NOI18N
        btnModificarEmpleado.setToolTipText("ACTUALIZAR DATOS");

        btnEliminarEmpleado.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmpleadoBuscar72.png"))); // NOI18N
        btnEliminarEmpleado.setToolTipText("ELIMINAR");

        btnCuentasRegistradas.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmpleadoEliminar72.png"))); // NOI18N
        btnCuentasRegistradas.setToolTipText("ESTADO DE CUENTA");

        btnCuentasRegistradas1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/EmpleadoCuentas72.png"))); // NOI18N
        btnCuentasRegistradas1.setToolTipText("ESTADO DE CUENTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(21, Short.MAX_VALUE)
                .addComponent(btnRegistrarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnModificarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnEliminarEmpleado)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCuentasRegistradas)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnCuentasRegistradas1)
                .addGap(19, 19, 19))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCuentasRegistradas1)
                    .addComponent(btnCuentasRegistradas)
                    .addComponent(btnEliminarEmpleado)
                    .addComponent(btnModificarEmpleado)
                    .addComponent(btnRegistrarEmpleado))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarEmpleadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarEmpleadoMouseClicked
        // TODO add your handling code here:
        PnlEmp_Registrar empReg = new PnlEmp_Registrar();   
        empReg.setSize(300,500);
        empReg.setLocation(0,0);
        FrmAdministrador.PanelAdministrador.setVisible(true);
        FrmAdministrador.PanelAdministrador.removeAll();
        FrmAdministrador.PanelAdministrador.add(empReg,BorderLayout.CENTER);
        FrmAdministrador.PanelAdministrador.revalidate();
        FrmAdministrador.PanelAdministrador.repaint();
    }//GEN-LAST:event_btnRegistrarEmpleadoMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btnCuentasRegistradas;
    private javax.swing.JLabel btnCuentasRegistradas1;
    private javax.swing.JLabel btnEliminarEmpleado;
    private javax.swing.JLabel btnModificarEmpleado;
    private javax.swing.JLabel btnRegistrarEmpleado;
    // End of variables declaration//GEN-END:variables
}
