/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package presentacion;

import java.awt.BorderLayout;
import javax.swing.JOptionPane;

/**
 *
 * @author COMPAQ
 */
public class PnlSucu_Control extends javax.swing.JPanel {

    /**
     * Creates new form PnlClie_Control
     */
    public PnlSucu_Control() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnRegistrarSucursal = new javax.swing.JLabel();
        btnModificarSucursal = new javax.swing.JLabel();
        btnBuscarSucursal = new javax.swing.JLabel();
        btn = new javax.swing.JLabel();

        setOpaque(false);

        btnRegistrarSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SucursalRegistrar72.png"))); // NOI18N
        btnRegistrarSucursal.setToolTipText("REGISTRAR");
        btnRegistrarSucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarSucursalMouseClicked(evt);
            }
        });

        btnModificarSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SucursalModificar72.png"))); // NOI18N
        btnModificarSucursal.setToolTipText("ACTUALIZAR DATOS");

        btnBuscarSucursal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SucursalBuscar72.png"))); // NOI18N
        btnBuscarSucursal.setToolTipText("ELIMINAR");
        btnBuscarSucursal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBuscarSucursalMouseClicked(evt);
            }
        });

        btn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/SucursalEliminar72.png"))); // NOI18N
        btn.setToolTipText("ESTADO DE CUENTA");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(48, 48, 48)
                .addComponent(btnRegistrarSucursal)
                .addGap(18, 18, 18)
                .addComponent(btnModificarSucursal)
                .addGap(18, 18, 18)
                .addComponent(btnBuscarSucursal)
                .addGap(18, 18, 18)
                .addComponent(btn)
                .addContainerGap(50, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn)
                    .addComponent(btnBuscarSucursal)
                    .addComponent(btnModificarSucursal)
                    .addComponent(btnRegistrarSucursal))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarSucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarSucursalMouseClicked
        // TODO add your handling code here:
        PnlSucu_Registrar sucuReg = new PnlSucu_Registrar();   
        sucuReg.setSize(300,500);
        sucuReg.setLocation(0,0);
        FrmAdministrador.PanelAdministrador.setVisible(true);
        FrmAdministrador.PanelAdministrador.removeAll();
        FrmAdministrador.PanelAdministrador.add(sucuReg,BorderLayout.CENTER);
        FrmAdministrador.PanelAdministrador.revalidate();
        FrmAdministrador.PanelAdministrador.repaint();
    }//GEN-LAST:event_btnRegistrarSucursalMouseClicked

    private void btnBuscarSucursalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBuscarSucursalMouseClicked
        // TODO add your handling code here:
        String busqueda=JOptionPane.showInputDialog(null, "Buscar sucursal: ", "Busqueda", 3);
    }//GEN-LAST:event_btnBuscarSucursalMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel btn;
    private javax.swing.JLabel btnBuscarSucursal;
    private javax.swing.JLabel btnModificarSucursal;
    private javax.swing.JLabel btnRegistrarSucursal;
    // End of variables declaration//GEN-END:variables
}
